### ISSUE TITLE
Navigation scroll resets after click in a new page

### ISSUE THREAD

**Issue by Khanon** [mengxinssfd/typedoc-theme#10]
Do you have idea if this is a typedoc issue or it comes from the theme?  Here the link to a seemsly related question: [[link]]](https://github.com/TypeStrong/typedoc/issues/2626#issuecomment-2351747200)

Using the default typedoc theme this issue doesn't happen.

**Comment by mengxinssfd** [comment]
This theme is causing the problem, thanks for pointing it out

**Comment by Khanon** [comment]
The scroll is still moving when clicking on sidebar elements. It shouldn't move at all. Do you think this is fixable from your theme?

![scroll-top-issue](https://github.com/user-attachments/assets/665efae3-9727-4f92-911d-9901506a5434)
