### ISSUE TITLE
Support typedoc v0.25.1

### ISSUE THREAD

**Issue by hrueger** [mengxinssfd/typedoc-theme#3]
Hi @mengxinssfd,
we recently updated to typedoc v0.25.1 because we needed a new feature implemented there. However, npm complains that the range of the peer dep does not match. When using force it installs and builds successfully, however, all icons are gone:

<table>
<tr><td>Old Version (OK)</td>
<td>New Version (Broken)</td></tr>
<tr>
 <td>

![grafik](https://github.com/mengxinssfd/typedoc-theme/assets/18656830/2fda1429-897a-4157-acd5-15b5a8184162)

</td>
 <td>

![grafik](https://github.com/mengxinssfd/typedoc-theme/assets/18656830/02515c74-a355-4185-90ae-c56fa11dc423)

</td>

</tr>
</table>

**Comment by mengxinssfd** [comment]
Yes, typedoc v0.25.1 changed the way icon is used, I will fix it.

**Comment by hrueger** [comment]
Wow, that was was really fast. Thanks so much!

**Comment by mengxinssfd** [comment]
Haha, glad to help you.
