### ISSUE TITLE
Theme is not set for every page on Firefox

### ISSUE THREAD

**Issue by crystalfp** [mengxinssfd/typedoc-theme#5]
On Firefox 118.0.2 only the current page is put in dark mode if I change theme in settings of this page to "Dark". All other pages remains with theme "OS". And the theme for this page is saved and persists even restarting the browser.

The same thing does not happens on Chrome 118.0.5993.71 (Official Build) (64-bit). That is, all pages acquire the same theme.

I'm using typedoc 0.25.2 with "@mxssfd/typedoc-theme": "^1.1.3", on Windows 11 64-bits
Thanks for your help!
mario

**Comment by mengxinssfd** [comment]
Is this the reason?  https://github.com/TypeStrong/typedoc/issues/1707#issuecomment-932976304

**Comment by crystalfp** [comment]
Thanks for the explanation @mengxinssfd ! I will test with a web server soon.
Anyway, for my needs simply will open the documentation using Chrome.
Thanks again!
mario

**Comment by mengxinssfd** [comment]
You're welcome, I'm glad I can help you.
